version: '3.9'
services:
  api:
    container_name: restaurant-backend
    build: .
    restart: always
    ports:
    - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
            gunicorn restaurant.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app        