version: '3.9'

services:
  react-app:
    container_name: restaurant-frontend
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    command: >
      sh -c "yarn start"